In [ ]:
import pandas as pd

In [ ]:
data=pd.read_csv("/content/kepler_data (1).csv")

In [ ]:
data

kepid kepoi_name   kepler_name koi_disposition koi_pdisposition  \
0     10797460  K00752.01  Kepler-227 b       CONFIRMED        CANDIDATE   
1     10797460  K00752.02  Kepler-227 c       CONFIRMED        CANDIDATE   
2     10811496  K00753.01           NaN       CANDIDATE        CANDIDATE   
3     10848459  K00754.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
4     10854555  K00755.01  Kepler-664 b       CONFIRMED        CANDIDATE   
...        ...        ...           ...             ...              ...   
9559  10090151  K07985.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
9560  10128825  K07986.01           NaN       CANDIDATE        CANDIDATE   
9561  10147276  K07987.01           NaN  FALSE POSITIVE   FALSE POSITIVE   
9562  10155286  K07988.01           NaN       CANDIDATE        CANDIDATE   
9563  10156110  K07989.01           NaN  FALSE POSITIVE   FALSE POSITIVE   

      koi_score  koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  koi_fpflag_ec  \
0         1.000              0              0              0              0   
1         0.969              0              0              0              0   
2         0.000              0              0              0              0   
3         0.000              0              1              0              0   
4         1.000              0              0              0              0   
...         ...            ...            ...            ...            ...   
9559      0.000              0              1              1              0   
9560      0.497              0              0              0              0   
9561      0.021              0              0              1              0   
9562      0.092              0              0              0              0   
9563      0.000              0              0              1              1   

      ...  koi_steff_err2  koi_slogg  koi_slogg_err1  koi_slogg_err2  \
0     ...           -81.0      4.467           0.064          -0.096   
1     ...           -81.0      4.467           0.064          -0.096   
2     ...          -176.0      4.544           0.044          -0.176   
3     ...          -174.0      4.564           0.053          -0.168   
4     ...          -211.0      4.438           0.070          -0.210   
...   ...             ...        ...             ...             ...   
9559  ...          -166.0      4.529           0.035          -0.196   
9560  ...          -220.0      4.444           0.056          -0.224   
9561  ...          -236.0      4.447           0.056          -0.224   
9562  ...          -128.0      2.992           0.030          -0.027   
9563  ...          -225.0      4.385           0.054          -0.216   

      koi_srad  koi_srad_err1  koi_srad_err2         ra        dec  koi_kepmag  
0        0.927          0.105         -0.061  291.93423  48.141651      15.347  
1        0.927          0.105         -0.061  291.93423  48.141651      15.347  
2        0.868          0.233         -0.078  297.00482  48.134129      15.436  
3        0.791          0.201         -0.067  285.53461  48.285210      15.597  
4        1.046          0.334         -0.133  288.75488  48.226200      15.509  
...        ...            ...            ...        ...        ...         ...  
9559     0.903          0.237         -0.079  297.18875  47.093819      14.082  
9560     1.031          0.341         -0.114  286.50937  47.163219      14.757  
9561     1.041          0.341         -0.114  294.16489  47.176281      15.385  
9562     7.824          0.223         -1.896  296.76288  47.145142      10.998  
9563     1.193          0.410         -0.137  297.00977  47.121021      14.826  

[9564 rows x 49 columns]

In [ ]:
data['koi_steff_err2'].value_counts()

-79.0     142
-152.0    128
-78.0     128
-169.0    118
-159.0    116
         ... 
-450.0      1
-380.0      1
-426.0      1
-350.0      1
-41.0       1
Name: koi_steff_err2, Length: 376, dtype: int64

In [ ]:
kepler_name

In [ ]:
data.describe()

kepid    koi_score  koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  \
count  9.564000e+03  8054.000000    9564.000000    9564.000000    9564.000000   
mean   7.690628e+06     0.480829       0.208595       0.232748       0.197512   
std    2.653459e+06     0.476928       4.767290       0.422605       0.398142   
min    7.574500e+05     0.000000       0.000000       0.000000       0.000000   
25%    5.556034e+06     0.000000       0.000000       0.000000       0.000000   
50%    7.906892e+06     0.334000       0.000000       0.000000       0.000000   
75%    9.873066e+06     0.998000       0.000000       0.000000       0.000000   
max    1.293514e+07     1.000000     465.000000       1.000000       1.000000   

       koi_fpflag_ec     koi_period  koi_period_err1  koi_period_err2  \
count    9564.000000    9564.000000      9110.000000      9110.000000   
mean        0.120033      75.671358         0.002148        -0.002148   
std         0.325018    1334.744046         0.008243         0.008243   
min         0.000000       0.241843         0.000000        -0.173000   
25%         0.000000       2.733684         0.000005        -0.000276   
50%         0.000000       9.752831         0.000035        -0.000035   
75%         0.000000      40.715178         0.000276        -0.000005   
max         1.000000  129995.778400         0.173000         0.000000   

       koi_time0bk  ...  koi_steff_err2    koi_slogg  koi_slogg_err1  \
count  9564.000000  ...     9081.000000  9201.000000     9096.000000   
mean    166.183251  ...     -162.265059     4.310157        0.120738   
std      67.918960  ...       72.746348     0.432606        0.132837   
min     120.515914  ...    -1762.000000     0.047000        0.000000   
25%     132.761718  ...     -198.000000     4.218000        0.042000   
50%     137.224595  ...     -160.000000     4.438000        0.070000   
75%     170.694603  ...     -114.000000     4.543000        0.149000   
max    1472.522306  ...        0.000000     5.364000        1.472000   

       koi_slogg_err2     koi_srad  koi_srad_err1  koi_srad_err2           ra  \
count     9096.000000  9201.000000    9096.000000    9096.000000  9564.000000   
mean        -0.143161     1.728712       0.362292      -0.394806   292.060163   
std          0.085477     6.127185       0.930870       2.168213     4.766657   
min         -1.207000     0.109000       0.000000    -116.137000   279.852720   
25%         -0.196000     0.829000       0.129000      -0.250000   288.660770   
50%         -0.128000     1.000000       0.251000      -0.111000   292.261125   
75%         -0.088000     1.345000       0.364000      -0.069000   295.859160   
max          0.000000   229.908000      33.091000       0.000000   301.720760   

               dec   koi_kepmag  
count  9564.000000  9563.000000  
mean     43.810433    14.264606  
std       3.601243     1.385448  
min      36.577381     6.966000  
25%      40.777173    13.440000  
50%      43.677504    14.520000  
75%      46.714611    15.322000  
max      52.336010    20.003000  

[8 rows x 44 columns]

In [ ]:
data.info()

In [ ]:
data.isnull().sum().sort_values()

In [ ]:
import seaborn as sns
sns.heatmap(data.corr())

In [ ]:
data=data.drop(columns=["koi_tedaq_err2","koi_teq_err1","kepoi_name","kepler_name"])

In [ ]:
pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', None)

In [ ]:
data.head(10)

kepid koi_disposition koi_pdisposition  koi_score  koi_fpflag_nt  \
0  10797460       CONFIRMED        CANDIDATE      1.000              0   
1  10797460       CONFIRMED        CANDIDATE      0.969              0   
2  10811496       CANDIDATE        CANDIDATE      0.000              0   
3  10848459  FALSE POSITIVE   FALSE POSITIVE      0.000              0   
4  10854555       CONFIRMED        CANDIDATE      1.000              0   
5  10872983       CONFIRMED        CANDIDATE      1.000              0   
6  10872983       CONFIRMED        CANDIDATE      1.000              0   
7  10872983       CONFIRMED        CANDIDATE      0.992              0   
8   6721123  FALSE POSITIVE   FALSE POSITIVE      0.000              0   
9  10910878       CONFIRMED        CANDIDATE      1.000              0   

   koi_fpflag_ss  koi_fpflag_co  koi_fpflag_ec  koi_period  koi_period_err1  \
0              0              0              0    9.488036     2.780000e-05   
1              0              0              0   54.418383     2.480000e-04   
2              0              0              0   19.899140     1.490000e-05   
3              1              0              0    1.736952     2.630000e-07   
4              0              0              0    2.525592     3.760000e-06   
5              0              0              0   11.094321     2.040000e-05   
6              0              0              0    4.134435     1.050000e-05   
7              0              0              0    2.566589     1.780000e-05   
8              1              1              0    7.361790     2.130000e-05   
9              0              0              0   16.068647     1.090000e-05   

   koi_period_err2  koi_time0bk  koi_time0bk_err1  koi_time0bk_err2  \
0    -2.780000e-05   170.538750          0.002160         -0.002160   
1    -2.480000e-04   162.513840          0.003520         -0.003520   
2    -1.490000e-05   175.850252          0.000581         -0.000581   
3    -2.630000e-07   170.307565          0.000115         -0.000115   
4    -3.760000e-06   171.595550          0.001130         -0.001130   
5    -2.040000e-05   171.201160          0.001410         -0.001410   
6    -1.050000e-05   172.979370          0.001900         -0.001900   
7    -1.780000e-05   179.554370          0.004610         -0.004610   
8    -2.130000e-05   132.250530          0.002530         -0.002530   
9    -1.090000e-05   173.621937          0.000517         -0.000517   

   koi_impact  koi_impact_err1  koi_impact_err2  koi_duration  \
0       0.146            0.318           -0.146       2.95750   
1       0.586            0.059           -0.443       4.50700   
2       0.969            5.126           -0.077       1.78220   
3       1.276            0.115           -0.092       2.40641   
4       0.701            0.235           -0.478       1.65450   
5       0.538            0.030           -0.428       4.59450   
6       0.762            0.139           -0.532       3.14020   
7       0.755            0.212           -0.523       2.42900   
8       1.169            7.133           -0.044       5.02200   
9       0.052            0.262           -0.052       3.53470   

   koi_duration_err1  koi_duration_err2  koi_depth  koi_depth_err1  \
0            0.08190           -0.08190      616.0            19.5   
1            0.11600           -0.11600      875.0            35.5   
2            0.03410           -0.03410    10800.0           171.0   
3            0.00537           -0.00537     8080.0            12.8   
4            0.04200           -0.04200      603.0            16.9   
5            0.06100           -0.06100     1520.0            24.2   
6            0.06730           -0.06730      686.0            18.7   
7            0.16500           -0.16500      227.0            16.8   
8            0.13600           -0.13600      234.0             5.8   
9            0.02410           -0.02410     4910.0            33.3   

   koi_depth_err2  koi_prad  koi_prad_err1  koi_prad

In [ ]:
data["koi_pdisposition"].value_counts()

FALSE POSITIVE    4847
CANDIDATE         4717
Name: koi_pdisposition, dtype: int64

In [ ]:
from sklearn import preprocessing
  
# label_encoder object knows how to understand word labels.
label_encoder = preprocessing.LabelEncoder()
  
# Encode labels in column 'species'.
data['koi_pdisposition']= label_encoder.fit_transform(data['koi_pdisposition'])

In [ ]:
data['koi_tce_delivname']= label_encoder.fit_transform(data['koi_tce_delivname'])

In [ ]:
data['koi_disposition']= label_encoder.fit_transform(data['koi_disposition'])

In [ ]:
data.head(10)

kepid  koi_disposition  koi_pdisposition  koi_score  koi_fpflag_nt  \
0  10797460                1                 0      1.000              0   
1  10797460                1                 0      0.969              0   
2  10811496                0                 0      0.000              0   
3  10848459                2                 1      0.000              0   
4  10854555                1                 0      1.000              0   
5  10872983                1                 0      1.000              0   
6  10872983                1                 0      1.000              0   
7  10872983                1                 0      0.992              0   
8   6721123                2                 1      0.000              0   
9  10910878                1                 0      1.000              0   

   koi_fpflag_ss  koi_fpflag_co  koi_fpflag_ec  koi_period  koi_period_err1  \
0              0              0              0    9.488036     2.780000e-05   
1              0              0              0   54.418383     2.480000e-04   
2              0              0              0   19.899140     1.490000e-05   
3              1              0              0    1.736952     2.630000e-07   
4              0              0              0    2.525592     3.760000e-06   
5              0              0              0   11.094321     2.040000e-05   
6              0              0              0    4.134435     1.050000e-05   
7              0              0              0    2.566589     1.780000e-05   
8              1              1              0    7.361790     2.130000e-05   
9              0              0              0   16.068647     1.090000e-05   

   koi_period_err2  koi_time0bk  koi_time0bk_err1  koi_time0bk_err2  \
0    -2.780000e-05   170.538750          0.002160         -0.002160   
1    -2.480000e-04   162.513840          0.003520         -0.003520   
2    -1.490000e-05   175.850252          0.000581         -0.000581   
3    -2.630000e-07   170.307565          0.000115         -0.000115   
4    -3.760000e-06   171.595550          0.001130         -0.001130   
5    -2.040000e-05   171.201160          0.001410         -0.001410   
6    -1.050000e-05   172.979370          0.001900         -0.001900   
7    -1.780000e-05   179.554370          0.004610         -0.004610   
8    -2.130000e-05   132.250530          0.002530         -0.002530   
9    -1.090000e-05   173.621937          0.000517         -0.000517   

   koi_impact  koi_impact_err1  koi_impact_err2  koi_duration  \
0       0.146            0.318           -0.146       2.95750   
1       0.586            0.059           -0.443       4.50700   
2       0.969            5.126           -0.077       1.78220   
3       1.276            0.115           -0.092       2.40641   
4       0.701            0.235           -0.478       1.65450   
5       0.538            0.030           -0.428       4.59450   
6       0.762            0.139           -0.532       3.14020   
7       0.755            0.212           -0.523       2.42900   
8       1.169            7.133           -0.044       5.02200   
9       0.052            0.262           -0.052       3.53470   

   koi_duration_err1  koi_duration_err2  koi_depth  koi_depth_err1  \
0            0.08190           -0.08190      616.0            19.5   
1            0.11600           -0.11600      875.0            35.5   
2            0.03410           -0.03410    10800.0           171.0   
3            0.00537           -0.00537     8080.0            12.8   
4            0.04200           -0.04200      603.0            16.9   
5            0.06100           -0.06100     1520.0            24.2   
6            0.06730           -0.06730      686.0            18.7   
7            0.16500           -0.16500      227.0            16.8   
8            0.13600           -0.13600      234.0             5.8   
9            0.02410           -0.02410     4910.0            33.3   

   koi_depth_err2  koi_prad  k

In [ ]:
lis=list(data.columns)
lis

In [ ]:
for col in lis:
  print(col+":-")
  print(data[col].value_counts())
  print()

In [ ]:
data=data.fillna(data.mean())

In [ ]:
X=data.drop(columns=["koi_disposition"])

In [ ]:
X

kepid  koi_pdisposition  koi_score  koi_fpflag_nt  koi_fpflag_ss  \
0     10797460                 0      1.000              0              0   
1     10797460                 0      0.969              0              0   
2     10811496                 0      0.000              0              0   
3     10848459                 1      0.000              0              1   
4     10854555                 0      1.000              0              0   
...        ...               ...        ...            ...            ...   
9559  10090151                 1      0.000              0              1   
9560  10128825                 0      0.497              0              0   
9561  10147276                 1      0.021              0              0   
9562  10155286                 0      0.092              0              0   
9563  10156110                 1      0.000              0              0   

      koi_fpflag_co  koi_fpflag_ec  koi_period  koi_period_err1  \
0                 0              0    9.488036     2.780000e-05   
1                 0              0   54.418383     2.480000e-04   
2                 0              0   19.899140     1.490000e-05   
3                 0              0    1.736952     2.630000e-07   
4                 0              0    2.525592     3.760000e-06   
...             ...            ...         ...              ...   
9559              1              0    0.527699     1.160000e-07   
9560              0              0    1.739849     1.780000e-05   
9561              1              0    0.681402     2.430000e-06   
9562              0              0  333.486169     4.240000e-03   
9563              1              1    4.856035     6.360000e-05   

      koi_period_err2  koi_time0bk  koi_time0bk_err1  koi_time0bk_err2  \
0       -2.780000e-05   170.538750          0.002160         -0.002160   
1       -2.480000e-04   162.513840          0.003520         -0.003520   
2       -1.490000e-05   175.850252          0.000581         -0.000581   
3       -2.630000e-07   170.307565          0.000115         -0.000115   
4       -3.760000e-06   171.595550          0.001130         -0.001130   
...               ...          ...               ...               ...   
9559    -1.160000e-07   131.705093          0.000170         -0.000170   
9560    -1.780000e-05   133.001270          0.007690         -0.007690   
9561    -2.430000e-06   132.181750          0.002850         -0.002850   
9562    -4.240000e-03   153.615010          0.005070         -0.005070   
9563    -6.360000e-05   135.993300          0.010800         -0.010800   

      koi_impact  koi_impact_err1  koi_impact_err2  koi_duration  \
0          0.146            0.318           -0.146       2.95750   
1          0.586            0.059           -0.443       4.50700   
2          0.969            5.126           -0.077       1.78220   
3          1.276            0.115           -0.092       2.40641   
4          0.701            0.235           -0.478       1.65450   
...          ...              ...              ...           ...   
9559       1.252            0.051           -0.049       3.22210   
9560       0.043            0.423           -0.043       3.11400   
9561       0.147            0.309           -0.147       0.86500   
9562       0.214            0.255           -0.214       3.19900   
9563       0.134            0.323           -0.134       3.07800   

      koi_duration_err1  koi_duration_err2  koi_depth  koi_depth_err1  \
0               0.08190           -0.08190      616.0            19.5   
1               0.11600           -0.11600      875.0            35.5   
2               0.03410           -0.03410    10800.0           171.0   
3               0.00537           -0.00537     8080.0            12.8   
4               0.04200           -0.04200      603.0            16.9   
...                 ...                ...        ...             ...   
9559            0.01740           -0.01740     1580.0         

In [ ]:
y=data["koi_disposition"]
y

0       1
1       1
2       0
3       2
4       1
       ..
9559    2
9560    0
9561    2
9562    0
9563    2
Name: koi_disposition, Length: 9564, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_rem, y_train, y_rem = train_test_split(X,y, train_size=0.8)

# Now since we want the valid and test size to be equal (10% each of overall data). 
# we have to define valid_size=0.5 (that is 50% of remaining data)
test_size = 0.5
X_valid, X_test, y_valid, y_test = train_test_split(X_rem,y_rem, test_size=0.5)


In [ ]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(max_depth=2, random_state=0)
clf.fit(X_train, y_train)


RandomForestClassifier(max_depth=2, random_state=0)

In [ ]:
y_pred=clf.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report
target_names = ['class 0', 'class 1', 'class 2']
print(classification_report(y_test, y_pred, target_names=target_names))

              precision    recall  f1-score   support

     class 0       0.95      0.56      0.70       241
     class 1       0.76      0.96      0.85       241
     class 2       0.92      1.00      0.96       475

    accuracy                           0.88       957
   macro avg       0.88      0.84      0.84       957
weighted avg       0.89      0.88      0.87       957



In [ ]:
# evaluate a logistic regression model using k-fold cross-validation
from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
# create dataset
# X, y = make_classification(n_samples=1000, n_features=20, n_informative=15, n_redundant=5, random_state=1)
# prepare the cross-validation procedure
cv = KFold(n_splits=10, random_state=1, shuffle=True)
# create model
# model = LogisticRegression()
# evaluate model
scores = cross_val_score(clf, X, y, scoring='accuracy', cv=cv, n_jobs=-1)
# report performance
print('Accuracy: %.3f (%.3f)' % (mean(scores), std(scores)))

Accuracy: 0.861 (0.006)


In [ ]:
## ---------- XGBoost model v1 ----------
## base run of model with default hyperparameters
import xgboost as xgb
from sklearn.model_selection import train_test_split, GridSearchCV
# from sklearn.metrics import confusion_matrix, plot_confusion_matrix, classification_report
from sklearn.metrics import balanced_accuracy_score, accuracy_score, precision_score, recall_score, f1_score
from sklearn.utils.class_weight import compute_sample_weight
xgb_clf = xgb.XGBClassifier(objective='multi:softmax', 
                            num_class=3, 
                            missing=1, 
                            early_stopping_rounds=10, 
                            eval_metric=['merror','mlogloss'], 
                            seed=42)
xgb_clf.fit(X_train, 
            y_train,
            verbose=0, # set to 1 to see xgb training round intermediate results
            eval_set=[(X_train, y_train), (X_test, y_test)])

# preparing evaluation metric plots
results = xgb_clf.evals_result()
epochs = len(results['validation_0']['mlogloss'])
x_axis = range(0, epochs)


## ---------- Model Classification Report ----------
## get predictions and create model quality report

y_pred = xgb_clf.predict(X_test)

print('\n------------------ Confusion Matrix -----------------\n')
print(confusion_matrix(y_test, y_pred))

print('\n-------------------- Key Metrics --------------------')
print('\nAccuracy: {:.2f}'.format(accuracy_score(y_test, y_pred)))
print('Balanced Accuracy: {:.2f}\n'.format(balanced_accuracy_score(y_test, y_pred)))

print('Micro Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_test, y_pred, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_test, y_pred, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_test, y_pred, average='weighted')))

print('\n--------------- Classification Report ---------------\n')
print(classification_report(y_test, y_pred))
print('---------------------- XGBoost ----------------------') # unnecessary fancy styling


------------------ Confusion Matrix -----------------

[[199  42   0]
 [ 22 219   0]
 [  0   0 475]]

-------------------- Key Metrics --------------------

Accuracy: 0.93
Balanced Accuracy: 0.91

Micro Precision: 0.93
Micro Recall: 0.93
Micro F1-score: 0.93

Macro Precision: 0.91
Macro Recall: 0.91
Macro F1-score: 0.91

Weighted Precision: 0.93
Weighted Recall: 0.93
Weighted F1-score: 0.93

--------------- Classification Report ---------------

              precision    recall  f1-score   support

           0       0.90      0.83      0.86       241
           1       0.84      0.91      0.87       241
           2       1.00      1.00      1.00       475

    accuracy                           0.93       957
   macro avg       0.91      0.91      0.91       957
weighted avg       0.93      0.93      0.93       957

---------------------- XGBoost ----------------------


In [ ]:
## ---------- XGBoost model v2 ----------
## second run of model with "optimized" hyperparameters 

# declaring and fitting xgb classifier
xgb_clf = xgb.XGBClassifier(objective='multi:softmax', 
                            num_class=3, 
                            missing=1,
                            gamma=0, # default gamma value
                            learning_rate=0.1,
                            max_depth=3,
                            reg_lambda=1, # default L2 value
                            subsample=1, # default subsample value
                            colsample_bytree=1, # default colsample_bytree value
                            early_stopping_rounds=10,
                            eval_metric=['merror','mlogloss'],
                            seed=42)
xgb_clf.fit(X_train, 
            y_train,
            verbose=0, # set to 1 to see xgb training round intermediate results
            #sample_weight=sample_weights, # class weights to combat unbalanced 'target'
            eval_set=[(X_train, y_train), (X_test, y_test)])

# preparing evaluation metric plots
results = xgb_clf.evals_result()
epochs = len(results['validation_0']['mlogloss'])
x_axis = range(0, epochs)


## ---------- Model Classification Report ----------
## get predictions and create model quality report

y_pred = xgb_clf.predict(X_test)

print('\n------------------ Confusion Matrix -----------------\n')
print(confusion_matrix(y_test, y_pred))

print('\nAccuracy: {:.2f}'.format(accuracy_score(y_test, y_pred)))
print('Balanced Accuracy: {:.2f}\n'.format(balanced_accuracy_score(y_test, y_pred)))

print('Micro Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_test, y_pred, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_test, y_pred, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_test, y_pred, average='weighted')))

print('\n--------------- Classification Report ---------------\n')
print(classification_report(y_test, y_pred))
print('---------------------- XGBoost ----------------------') # unnecessary fancy styling


------------------ Confusion Matrix -----------------

[[196  45   0]
 [ 17 224   0]
 [  0   0 475]]

Accuracy: 0.94
Balanced Accuracy: 0.91

Micro Precision: 0.94
Micro Recall: 0.94
Micro F1-score: 0.94

Macro Precision: 0.92
Macro Recall: 0.91
Macro F1-score: 0.91

Weighted Precision: 0.94
Weighted Recall: 0.94
Weighted F1-score: 0.93

--------------- Classification Report ---------------

              precision    recall  f1-score   support

           0       0.92      0.81      0.86       241
           1       0.83      0.93      0.88       241
           2       1.00      1.00      1.00       475

    accuracy                           0.94       957
   macro avg       0.92      0.91      0.91       957
weighted avg       0.94      0.94      0.93       957

---------------------- XGBoost ----------------------


In [ ]:
## ---------- XGBoost model v3 ----------
## third run of model with "optimized" hyperparameters and
## attempting to treat unbalanced target classes

# balancing 'target' class weights
sample_weights = compute_sample_weight(
    class_weight='balanced',
    y=y_train)

# declaring and fitting xgb classifier
xgb_clf = xgb.XGBClassifier(objective='multi:softmax', 
                            num_class=3, 
                            missing=1,
                            gamma=0, # default gamma value
                            learning_rate=0.1,
                            max_depth=5, # re-optimized from v2
                            reg_lambda=1, # default L2 value
                            #subsample=0.8, # tried but not ideal
                            #colsample_bytree=0.3, # tried but not ideal
                            early_stopping_rounds=10,
                            eval_metric=['merror','mlogloss'],
                            seed=42)
xgb_clf.fit(X_train, 
            y_train,
            verbose=0, # set to 1 to see xgb training round intermediate results
            sample_weight=sample_weights, # class weights to combat unbalanced 'target'
            eval_set=[(X_train, y_train), (X_test, y_test)])

# preparing evaluation metric plots
results = xgb_clf.evals_result()
epochs = len(results['validation_0']['mlogloss'])
x_axis = range(0, epochs)

## ---------- Model Classification Report ----------
## get predictions and create model quality report

y_pred = xgb_clf.predict(X_test)

print('\n------------------ Confusion Matrix -----------------\n')
print(confusion_matrix(y_test, y_pred))

print('\nAccuracy: {:.2f}'.format(accuracy_score(y_test, y_pred)))
print('Balanced Accuracy: {:.2f}\n'.format(balanced_accuracy_score(y_test, y_pred)))

print('Micro Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_test, y_pred, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_test, y_pred, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_test, y_pred, average='weighted')))

print('\n--------------- Classification Report ---------------\n')
print(classification_report(y_test, y_pred))
print('---------------------- XGBoost ----------------------') # unnecessary fancy styling


------------------ Confusion Matrix -----------------

[[201  40   0]
 [ 18 223   0]
 [  0   0 475]]

Accuracy: 0.94
Balanced Accuracy: 0.92

Micro Precision: 0.94
Micro Recall: 0.94
Micro F1-score: 0.94

Macro Precision: 0.92
Macro Recall: 0.92
Macro F1-score: 0.92

Weighted Precision: 0.94
Weighted Recall: 0.94
Weighted F1-score: 0.94

--------------- Classification Report ---------------

              precision    recall  f1-score   support

           0       0.92      0.83      0.87       241
           1       0.85      0.93      0.88       241
           2       1.00      1.00      1.00       475

    accuracy                           0.94       957
   macro avg       0.92      0.92      0.92       957
weighted avg       0.94      0.94      0.94       957

---------------------- XGBoost ----------------------
